version: '3'

services:
  server:
    env_file:
      - "./server/server.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "dnewton/dn-sample-server"
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "dnewton/dn-react-client"
    ports: 
      - "80:3000"
    links:
      - "server:rs"